import { defineCollection, z } from "astro:content";

const basePostSchema = z.object({
  title: z.string(),
  description: z.string(),
  date: z.coerce.date(),
  updated: z.coerce.date().optional(),
  tags: z.array(z.string()).default([]),
  category: z.string().optional(),
  contentType: z
    .enum([
      "troubleshooting-log",
      "terminal-log",
      "deployment-note",
      "implementation-note",
      "algorithm-study",
      "system-design",
      "infrastructure-decision",
      "debugging-note",
      "experiment-note",
      "paper-review",
      "engineering-observation"
    ])
    .optional(),
  draft: z.boolean().default(false),
  featured: z.boolean().default(false),
  autoGenerated: z.boolean().default(false),
  generatedAt: z.coerce.date().optional(),
  reviewed: z.boolean().default(true),
  reviewStatus: z.enum(["needs-review", "in-review", "reviewed"]).default("reviewed"),
  source: z.string().optional(),
  sourceUrl: z.string().url().optional(),
  sourceKind: z.enum(["raw-note", "terminal-log", "git-diff", "deployment-log", "study-note", "manual"]).optional(),
  sensitivity: z.enum(["public", "sanitized", "private-source"]).default("public"),
  techStack: z.array(z.string()).default([]),
  thumbnail: z.string().optional(),
  readingTime: z.string().optional()
});

const projects = defineCollection({
  type: "content",
  schema: basePostSchema.extend({
    role: z.string(),
    period: z.string(),
    githubUrl: z.string().url().optional(),
    externalUrl: z.string().url().optional(),
    status: z.enum(["planned", "building", "active", "archived"]).default("building")
  })
});

const notes = defineCollection({ type: "content", schema: basePostSchema });
const devops = defineCollection({ type: "content", schema: basePostSchema });
const research = defineCollection({ type: "content", schema: basePostSchema });
const autoArchive = defineCollection({ type: "content", schema: basePostSchema });

export const collections = {
  projects,
  notes,
  devops,
  research,
  "auto-archive": autoArchive
};
