import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const title = process.env.POST_TITLE ?? "Generated Draft";
const source = process.env.POST_SOURCE ?? "manual automation test";
const slug = title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
const targetDir = join(process.cwd(), "apps", "web", "src", "content", "auto-archive");
const targetFile = join(targetDir, `${slug}.mdx`);
const today = new Date().toISOString().slice(0, 10);

const body = `---
title: "${title.replaceAll('"', "'")}"
description: "AI-generated draft awaiting human review."
date: "${today}"
tags: ["generated", "review-needed"]
category: "auto-archive"
draft: true
featured: false
autoGenerated: true
source: "${source.replaceAll('"', "'")}"
techStack: []
---

## Review Checklist

- [ ] Verify source material.
- [ ] Remove private or sensitive data.
- [ ] Check commands, links, and dates.
- [ ] Add human context.
- [ ] Publish only by changing \`draft\` to \`false\`.

## Draft

Replace this section with the generated summary.
`;

await mkdir(targetDir, { recursive: true });
await writeFile(targetFile, body, "utf8");
console.log(`Created ${targetFile}`);
