import type { CollectionEntry, CollectionKey } from "astro:content";

type Entry = CollectionEntry<CollectionKey>;

export function isPublishedEntry(entry: Entry) {
  return !entry.data.draft && !(entry.data.autoGenerated && entry.data.reviewed === false);
}

export function byDateDesc(a: Entry, b: Entry) {
  return b.data.date.valueOf() - a.data.date.valueOf();
}

export function getCollectionUrl(entry: Entry) {
  return `/${entry.collection}/${entry.slug}/`;
}

export function normalizeTags(tags: string[] = []) {
  return tags.map((tag) => tag.trim()).filter(Boolean);
}

export function formatDate(date: Date) {
  return new Intl.DateTimeFormat("en", {
    year: "numeric",
    month: "short",
    day: "numeric"
  }).format(date);
}
